package com.sample.rules
import com.sample.Paciente;
import com.sample.Sintoma;
  
rule "Exantema 1"
salience 100
	when
		$s1:Sintoma(sintoma=="febre")
		$s2:Sintoma(sintoma=="manchas")
		$s3:Sintoma(sintoma=="dores")
		$p:Paciente(id==$s1.getIdPaciente(), id==$s2.getIdPaciente(), id==$s3.getIdPaciente(), idade>=15, diagnostico=="")
	then
		$p.setDiagnostico("Exantema 1");
		update($p);
		System.out.println("Paciente "+$p.getNome()+" foi diagnosticado com Exantema 1.");
end

rule "Exantema 2"
salience 90
	when
		$s1:Sintoma(sintoma=="febre")
		$s2:Sintoma(sintoma=="manchas")
		$p:Paciente(id==$s1.getIdPaciente(), id==$s2.getIdPaciente(), idade<15, diagnostico=="")
	then
		$p.setDiagnostico("Exantema 2");
		update($p);
		System.out.println("Paciente "+$p.getNome()+" foi diagnosticado com Exantema 2.");
end

rule "Gripe"
salience 80
	when
		$s1:Sintoma(sintoma=="febre")
		$s2:Sintoma(sintoma=="dores")
		$p:Paciente(id==$s1.getIdPaciente(), id==$s2.getIdPaciente(), diagnostico=="")
	then
		$p.setDiagnostico("Gripe");
		update($p);
		System.out.println("Paciente "+$p.getNome()+" foi diagnosticado com Gripe.");
end

rule "Resfriado"
salience 70
	when
		$s1:Sintoma(sintoma=="febre")
		$p:Paciente(id==$s1.getIdPaciente(), diagnostico=="")
	then
		$p.setDiagnostico("Resfriado");
		update($p);
		System.out.println("Paciente "+$p.getNome()+" foi diagnosticado com Resfriado.");
end

rule "Sem sintomas"
	when
		$p:Paciente(diagnostico=="")
		forall($s:Sintoma(idPaciente!=$p.getId()))
	then
		System.out.println("Paciente "+$p.getNome()+" sem sintomas!");
end