package com.sample.rules
import com.sample.Paciente;
import com.sample.Sintoma;
import com.sample.Diagnostico;
  
rule "Exantema 1"
salience 100
	when
		$s1:Sintoma(sintoma=="febre")
		$s2:Sintoma(sintoma=="manchas")
		$s3:Sintoma(sintoma=="dores")
		$p:Paciente(id==$s1.getIdPaciente(), id==$s2.getIdPaciente(), id==$s3.getIdPaciente(), idade>=15)
	then
		insert(new Diagnostico($p.getId(), $p.getNome(), "Exantema 1"));
		retract($p);
end

rule "Exantema 2"
salience 90
	when
		$s1:Sintoma(sintoma=="febre")
		$s2:Sintoma(sintoma=="manchas")
		$p:Paciente(id==$s1.getIdPaciente(), id==$s2.getIdPaciente(), idade<15)
	then
		insert(new Diagnostico($p.getId(), $p.getNome(), "Exantema 2"));
		retract($p);
end

rule "Gripe"
salience 80
	when
		$s1:Sintoma(sintoma=="febre")
		$s2:Sintoma(sintoma=="dores")
		$p:Paciente(id==$s1.getIdPaciente(), id==$s2.getIdPaciente())
	then
		insert(new Diagnostico($p.getId(), $p.getNome(), "Gripe"));
		retract($p);
end

rule "Resfriado"
salience 70
	when
		$s1:Sintoma(sintoma=="febre")
		$p:Paciente(id==$s1.getIdPaciente())
	then
		insert(new Diagnostico($p.getId(), $p.getNome(), "Resfriado"));
		retract($p);
end

rule "Com sintomas mas não correspondem a nenhum diagnóstico"
salience 10
	when
		$p1:Paciente()
	then
		insert(new Diagnostico($p1.getId(), $p1.getNome(), "Com sintomas, mas não correspondem a nenhum diagnóstico"));
		retract ($p1)
end

rule "Sem sintomas"
salience 11
	when
		$p:Paciente()
		forall($s:Sintoma(idPaciente!=$p.getId()))
	then
		insert(new Diagnostico($p.getId(), $p.getNome(), "Sem sintomas"));
		retract($p);
end

rule "Imprimir"
salience 0
	when
		$d:Diagnostico()
	then
		System.out.println("Paciente com id "+$d.getIdPaciente()+" "+$d.getNomePaciente()+" com diagnostico: "+$d.getDesignacao()+".");
end

rule "Inserir mais factos"
salience 110
	when
	then
		insert (new Paciente("006","Carlos Lopes",22));
		insert (new Paciente("007","Maria Ferreira",25));
		insert (new Paciente("008","Nuno Gomes",60));
		insert (new Paciente("009","Julio Lopes",58));
		insert (new Paciente("010","Rui Saraiva",45));
		insert (new Sintoma("006", "febre"));
		insert (new Sintoma("006", "dores"));
		insert (new Sintoma("006", "manchas"));
		insert (new Sintoma("007", "febre"));
		insert (new Sintoma("008", "dores"));
		insert (new Sintoma("010", "manchas"));
end